version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app

volumes:
  app_data: {}
